development:
  adapter: postgresql
  encoding: unicode
  database: time_to_ride_development
  pool: 5
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: time_to_ride_test
  pool: 5
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
