development:
  adapter: postgresql
  encoding: unicode
  database: time_to_ride_development
  pool: 5
  username: satindar
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: time_to_ride_test
  pool: 5
  username: satindar
  password:
